<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class OldCertificatesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $oldCertificates = [
            [
                'id' => 1,
                'student_id' => '158021',
                'student_name' => 'Mohamed Riyaf Fathima Sumaiya',
                'student_email' => 'mincingsumaiya@gmail.com',
                'student_phone' => 'N/A',
                'student_address' => 'N/A',
                'student_dob' => '2000-06-23',
                'gender' => null,
                'country' => null,
                'cumulative_credits_earned' => null,
                'cumulative_grade_point_average' => null,
                'proof_type' => 'Nic',
                'proof_id' => '200067504436',
                'reference_no' => 'VR102391-BA-9421',
                'course_name' => 'BA (Hons) Business Management',
                'course_duration' => '4 Years',
                'course_start_date' => '2020-04',
                'course_end_date' => '2024-05',
                'awarding_date' => '2024-04',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 2,
                'created_at' => '2024-05-09 17:49:34',
                'updated_at' => '2024-10-05 17:14:04',
            ],

            [
                'id' => 2,
                'student_id' => '158022',
                'student_name' => 'Sivakumar Mathushani',
                'student_email' => 'Mathushanisiva39@gmail.com',
                'student_phone' => 'N/A',
                'student_address' => 'N/A',
                'student_dob' => '2001-01-12',
                'gender' => null,
                'country' => null,
                'cumulative_credits_earned' => null,
                'cumulative_grade_point_average' => null,
                'proof_type' => 'Nic',
                'proof_id' => '200151202655',
                'reference_no' => 'VR102391-BA-9422',
                'course_name' => 'BA (Hons) Business Management',
                'course_duration' => '4 Years',
                'course_start_date' => '2020-04-05',
                'course_end_date' => '2024-03-25',
                'awarding_date' => '2024-04-10',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 2,
                'created_at' => '2024-05-09 17:53:28',
                'updated_at' => '2024-05-11 08:27:26',
            ],
            [
                'id' => 4,
                'student_id' => '158023',
                'student_name' => 'Nanduni Dilakshi Sumanasekara',
                'student_email' => 'ndunidilakshi@gmail.com',
                'student_phone' => 'N/A',
                'student_address' => 'N/A',
                'student_dob' => '1997-08-31',
                'gender' => null,
                'country' => null,
                'cumulative_credits_earned' => null,
                'cumulative_grade_point_average' => null,
                'proof_type' => 'Passport',
                'proof_id' => 'N8680228',
                'reference_no' => 'VR102391-BSc-9423',
                'course_name' => 'BSc (Hons) Psychology',
                'course_duration' => '3 Years',
                'course_start_date' => '2020-06-05',
                'course_end_date' => '2023-06-25',
                'awarding_date' => '2023-07-10',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 1,
                'created_at' => '2024-05-10 13:38:55',
                'updated_at' => '2024-05-11 08:35:59',
            ],
            [
                'id' => 6,
                'student_id' => '158020',
                'student_name' => 'Fathima Sharmin Mohamed Rizwan',
                'student_email' => 'sharriz786@gmail.com',
                'student_phone' => 'N/A',
                'student_address' => 'N/A',
                'student_dob' => '1986-08-30',
                'gender' => null,
                'country' => null,
                'cumulative_credits_earned' => null,
                'cumulative_grade_point_average' => null,
                'proof_type' => 'Passport',
                'proof_id' => 'N9525560',
                'reference_no' => 'VR102391-MBA-9420',
                'course_name' => 'Master of Business Administration',
                'course_duration' => '12 Months',
                'course_start_date' => '2023-03-05',
                'course_end_date' => '2024-03-25',
                'awarding_date' => '2024-03-25',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 2,
                'created_at' => '2024-05-11 07:49:50',
                'updated_at' => '2024-05-11 07:49:50',
            ],
            [
                'id' => 7,
                'student_id' => '158019',
                'student_name' => 'Sadiq Shaffee',
                'student_email' => 'sadiq.shafee81@gmail.com',
                'student_phone' => 'N/A',
                'student_address' => 'N/A',
                'student_dob' => '1981-05-01',
                'gender' => null,
                'country' => null,
                'cumulative_credits_earned' => null,
                'cumulative_grade_point_average' => null,
                'proof_type' => 'Nic',
                'proof_id' => '811221813V',
                'reference_no' => 'VR102391-BSc-9419',
                'course_name' => 'BSc (Hons) Business Management',
                'course_duration' => '3 Years',
                'course_start_date' => '2020-09-05',
                'course_end_date' => '2023-09-25',
                'awarding_date' => '2023-10-21',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 2,
                'created_at' => '2024-05-11 07:53:39',
                'updated_at' => '2024-05-11 07:53:39',
            ],
            [
                'id' => 8,
                'student_id' => '158018',
                'student_name' => 'Shalini Prasanna',
                'student_email' => 'N/A',
                'student_phone' => 'N/A',
                'student_address' => 'N/A',
                'student_dob' => '1994-02-01',
                'gender' => null,
                'country' => null,
                'cumulative_credits_earned' => null,
                'cumulative_grade_point_average' => null,
                'proof_type' => 'Nic',
                'proof_id' => '945320397V',
                'reference_no' => 'VR102391-BA-9418',
                'course_name' => 'BA (Hons) Business Management',
                'course_duration' => '4 Years',
                'course_start_date' => '2019-04-05',
                'course_end_date' => '2023-03-28',
                'awarding_date' => '2023-04-10',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 2,
                'created_at' => '2024-05-11 08:01:59',
                'updated_at' => '2024-05-11 08:29:06',
            ],
            [
                'id' => 9,
                'student_id' => '158017',
                'student_name' => 'Fathima Miffrah Murusalin',
                'student_email' => 'N/A',
                'student_phone' => 'N/A',
                'student_address' => 'N/A',
                'student_dob' => '1994-05-08',
                'gender' => null,
                'country' => null,
                'cumulative_credits_earned' => null,
                'cumulative_grade_point_average' => null,
                'proof_type' => 'Nic',
                'proof_id' => '946292273V',
                'reference_no' => 'VR102391-BA-9417',
                'course_name' => 'Bachelor of Business Administration (Hons)',
                'course_duration' => '4 Years',
                'course_start_date' => '2018-04-05',
                'course_end_date' => '2022-03-28',
                'awarding_date' => '2022-04-10',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 2,
                'created_at' => '2024-05-11 08:10:20',
                'updated_at' => '2024-05-11 08:29:57',
            ],
            [
                'id' => 10,
                'student_id' => '158016',
                'student_name' => 'Mohamed Azmy Zainab',
                'student_email' => 'N/A',
                'student_phone' => 'N/A',
                'student_address' => 'N/A',
                'student_dob' => '1994-04-28',
                'gender' => null,
                'country' => null,
                'cumulative_credits_earned' => null,
                'cumulative_grade_point_average' => null,
                'proof_type' => 'Nic',
                'proof_id' => '946194719V',
                'reference_no' => 'VR102391-BA-9416',
                'course_name' => 'Bachelor of Business Management',
                'course_duration' => '4 Years',
                'course_start_date' => '2018-04',
                'course_end_date' => '2022-03',
                'awarding_date' => '2022-04',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 2,
                'created_at' => '2024-05-11 08:14:37',
                'updated_at' => '2024-10-11 12:16:54',
            ],
            [
                'id' => 11,
                'student_id' => '158015',
                'student_name' => 'Mohamed Ashraff Umar',
                'student_email' => 'rismy23@gmail.com',
                'student_phone' => 'N/A',
                'student_address' => 'N/A',
                'student_dob' => '2002-11-16',
                'gender' => null,
                'country' => null,
                'cumulative_credits_earned' => null,
                'cumulative_grade_point_average' => null,
                'proof_type' => 'Nic',
                'proof_id' => 'N/A',
                'reference_no' => 'VR102391-BA-9415',
                'course_name' => 'Bachelor of Business Management (Hons)',
                'course_duration' => '3 Years',
                'course_start_date' => '2021-01-10',
                'course_end_date' => '2023-12-23',
                'awarding_date' => '2023-02-05',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 2,
                'created_at' => '2024-05-11 08:18:10',
                'updated_at' => '2024-05-11 08:31:47',
            ],
            [
                'id' => 12,
                'student_id' => '158024',
                'student_name' => 'R. M. Madusanka Nuwan Kumara Rathnayake',
                'student_email' => 'nuwan1101@live.com',
                'student_phone' => 'N/A',
                'student_address' => 'N/A',
                'student_dob' => '1989-04-12',
                'gender' => null,
                'country' => null,
                'cumulative_credits_earned' => null,
                'cumulative_grade_point_average' => null,
                'proof_type' => 'Nic',
                'proof_id' => '891031181V',
                'reference_no' => 'VR102391-BSc-9424',
                'course_name' => 'BSc (Hons) Cyber Security and Networking',
                'course_duration' => '4 Years',
                'course_start_date' => '2018-05-05',
                'course_end_date' => '2022-05-25',
                'awarding_date' => '2022-05-25',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 2,
                'created_at' => '2024-05-14 11:56:44',
                'updated_at' => '2024-05-14 11:56:44',
            ],
            [
                'id' => 13,
                'student_id' => '85007-TH-789',
                'student_name' => 'Kalahe Arachchige Padmin Malinda Bandara Kalahe',
                'student_email' => 'N/A',
                'student_phone' => 'N/A',
                'student_address' => 'N/A',
                'student_dob' => 'N/A',
                'gender' => null,
                'country' => null,
                'cumulative_credits_earned' => null,
                'cumulative_grade_point_average' => null,
                'proof_type' => 'Nic',
                'proof_id' => 'N/A',
                'reference_no' => '85007-TH-789',
                'course_name' => 'BSc (Hons) Tourism and Hospitality Management',
                'course_duration' => '3 Years',
                'course_start_date' => 'June 2018',
                'course_end_date' => 'June 2021',
                'awarding_date' => 'July 2021',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 2,
                'created_at' => '2024-05-29 11:03:58',
                'updated_at' => '2024-05-29 11:03:58',
            ],
            [
                'id' => 14,
                'student_id' => '158025',
                'student_name' => 'Mohamed Azmie Abdul Malik',
                'student_email' => 'abdulmalikazmi554@gmail.com',
                'student_phone' => '0752400633',
                'student_address' => '100/3b Wijayavimalarathna Mawatha, Maha Buthgamuwa,Angoda',
                'student_dob' => '1990-12-14',
                'gender' => null,
                'country' => null,
                'cumulative_credits_earned' => null,
                'cumulative_grade_point_average' => null,
                'proof_type' => 'Passport',
                'proof_id' => 'N5149128',
                'reference_no' => 'VR102392-BSc-9425',
                'course_name' => 'Bachelor of Science (Hons) Information Technology',
                'course_duration' => '4 Years',
                'course_start_date' => '2014-06-05',
                'course_end_date' => '2018-06-28',
                'awarding_date' => '2018-06-28',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 2,
                'created_at' => '2024-07-02 16:53:44',
                'updated_at' => '2024-07-02 16:53:44',
            ],
            [
                'id' => 15,
                'student_id' => '158026',
                'student_name' => 'Danshika Jensteepan',
                'student_email' => 'danshikasteepan@gmail.com',
                'student_phone' => '0740411057',
                'student_address' => 'No 40/4, Singala school front lane,Kovil puthukkulam,Vavuniya',
                'student_dob' => '1998-09-17',
                'gender' => null,
                'country' => null,
                'cumulative_credits_earned' => null,
                'cumulative_grade_point_average' => null,
                'proof_type' => 'Nic',
                'proof_id' => '987611359V',
                'reference_no' => 'VR102392-BM-9426',
                'course_name' => 'Bachelor of Business Management',
                'course_duration' => '4 Years',
                'course_start_date' => '2018-11-05',
                'course_end_date' => '2022-11-25',
                'awarding_date' => '2022-12-10',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 2,
                'created_at' => '2024-07-11 12:15:53',
                'updated_at' => '2024-07-11 12:15:53',
            ],
            [
                'id' => 16,
                'student_id' => '158027',
                'student_name' => 'Malimage Shalini Shashikala Aponsu',
                'student_email' => 'shalinirock@hotmail.com',
                'student_phone' => '0760655782',
                'student_address' => '300/11, Visumpura, Ihala Karagahamuna , Ganemulla rd, Kadawatha',
                'student_dob' => '1985-07-05',
                'gender' => null,
                'country' => null,
                'cumulative_credits_earned' => null,
                'cumulative_grade_point_average' => null,
                'proof_type' => 'Passport',
                'proof_id' => 'N7325755',
                'reference_no' => 'VR102393-BSc-9427',
                'course_name' => 'London Business Campus (Awarded at Universidad Villa Rica)',
                'course_duration' => '12 Months',
                'course_start_date' => '2020-01',
                'course_end_date' => '2020-12',
                'awarding_date' => '2021-01',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 2,
                'created_at' => '2024-07-26 16:32:12',
                'updated_at' => '2024-07-27 20:26:51',
            ],
            [
                'id' => 17,
                'student_id' => '158028',
                'student_name' => 'Mohamed Armin Fathima Azra',
                'student_email' => 'azra8118@gmail.com',
                'student_phone' => '0777979938',
                'student_address' => '198/40, Ganithapura, Warakapola',
                'student_dob' => '1995-01-27',
                'gender' => null,
                'country' => null,
                'cumulative_credits_earned' => null,
                'cumulative_grade_point_average' => null,
                'proof_type' => 'Nic',
                'proof_id' => '955271572V',
                'reference_no' => 'VR102394-BA-9428',
                'course_name' => 'Bachelor of Arts (Hons) Early Childhood Education',
                'course_duration' => '3 Years',
                'course_start_date' => '2018-01-05',
                'course_end_date' => '2021-12-20',
                'awarding_date' => '2021-01-15',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 2,
                'created_at' => '2024-09-05 16:31:47',
                'updated_at' => '2024-09-05 16:31:47',
            ],
            [
                'id' => 18,
                'student_id' => '158029',
                'student_name' => 'Sereshe Asad Kariyawasam',
                'student_email' => 'sereshe1@gmail.com',
                'student_phone' => '0717350750',
                'student_address' => 'N/A',
                'student_dob' => '1982-04-08',
                'gender' => null,
                'country' => null,
                'cumulative_credits_earned' => null,
                'cumulative_grade_point_average' => null,
                'proof_type' => 'Nic',
                'proof_id' => '198209900714',
                'reference_no' => 'VR102394-BA-9429',
                'course_name' => 'Bachelor of Business Administration (Hons)',
                'course_duration' => '4 Years',
                'course_start_date' => '2009-01',
                'course_end_date' => '2012-12',
                'awarding_date' => '2013-01',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 2,
                'created_at' => '2024-09-24 10:24:19',
                'updated_at' => '2024-10-05 18:03:11',
            ],
            [
                'id' => 19,
                'student_id' => '158030',
                'student_name' => 'Kajeenthiran Sivanesan',
                'student_email' => 's.j.kajeenthran@gmail.com',
                'student_phone' => '0754881121',
                'student_address' => 'No:86 ,D10 , Uruththirapuram, Kilinochchi, Sri Lanka.',
                'student_dob' => '1998-05-27',
                'gender' => null,
                'country' => null,
                'cumulative_credits_earned' => null,
                'cumulative_grade_point_average' => null,
                'proof_type' => 'Nic',
                'proof_id' => '199814810344',
                'reference_no' => 'VR102395-BA-9430',
                'course_name' => 'Bachelor of Business Administration (Hons)',
                'course_duration' => '4 Years',
                'course_start_date' => '2020-04-10',
                'course_end_date' => '2024-03-30',
                'awarding_date' => '2024-04-20',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 2,
                'created_at' => '2024-09-28 09:42:39',
                'updated_at' => '2024-09-28 09:42:39',
            ],
            [
                'id' => 20,
                'student_id' => '158031',
                'student_name' => 'Mohamed Ziad Fathima Shehza',
                'student_email' => 'shehzaziad9@gmail.com',
                'student_phone' => '0754825815',
                'student_address' => 'No.95, Kandy Road, Gampola, Sri Lanka.',
                'student_dob' => '1994-02-17',
                'gender' => null,
                'country' => null,
                'cumulative_credits_earned' => null,
                'cumulative_grade_point_average' => null,
                'proof_type' => 'Nic',
                'proof_id' => '945480815V',
                'reference_no' => 'VR102396-BA-9431',
                'course_name' => 'Bachelor of Arts (Hons) Business Management',
                'course_duration' => '4 Years',
                'course_start_date' => '2020-04-05',
                'course_end_date' => '2024-03-28',
                'awarding_date' => '2024-04-10',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 2,
                'created_at' => '2024-09-30 12:16:55',
                'updated_at' => '2024-09-30 12:16:55',
            ],
            [
                'id' => 21,
                'student_id' => 'VR102390-BA-9414',
                'student_name' => 'Fathima Rushdha Muzammil Khan',
                'student_email' => null,
                'student_phone' => null,
                'student_address' => null,
                'student_dob' => '1987-08-24',
                'gender' => null,
                'country' => null,
                'cumulative_credits_earned' => null,
                'cumulative_grade_point_average' => null,
                'proof_type' => 'Nic',
                'proof_id' => 'N5550356',
                'reference_no' => 'VR102390-BA-9414',
                'course_name' => 'Bachelor of Education',
                'course_duration' => '3 Years',
                'course_start_date' => '2020-08',
                'course_end_date' => '2023-08',
                'awarding_date' => '2023-12',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 2,
                'created_at' => '2024-11-11 15:33:52',
                'updated_at' => '2024-11-11 15:33:52',
            ],
            [
                'id' => 22,
                'student_id' => '158032',
                'student_name' => 'THASNEEM AHAMED MOHAMED RIZVI',
                'student_email' => 'ahamedthasneem420@gmail.com',
                'student_phone' => '0763148834',
                'student_address' => 'REENIYAS VILLA, KULIYAPITYA ROAD, KOSGOLLA, HOROMBWA.',
                'student_dob' => '1999-04-18',
                'gender' => 'Male',
                'country' => 'Sri Lanka',
                'cumulative_credits_earned' => 360,
                'cumulative_grade_point_average' => '8.3',
                'proof_type' => 'Passport',
                'proof_id' => 'N9465023',
                'reference_no' => 'VR1702-BBA-FC-B24',
                'course_name' => 'BA (Hons) Business Management',
                'course_duration' => '3 years',
                'course_start_date' => '2021-02',
                'course_end_date' => '2024-02',
                'awarding_date' => '2024-04',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 1,
                'created_at' => '2024-12-04 21:33:51',
                'updated_at' => '2025-02-10 13:19:37',
            ],
            [
                'id' => 24,
                'student_id' => '158033',
                'student_name' => 'Thalis Kolamunna Galganage Mary Virgin',
                'student_email' => 'annvirgy3@gmail.com',
                'student_phone' => '94778355950',
                'student_address' => '282/1 Kadawatha road Dehiwala',
                'student_dob' => '1973-05-31',
                'gender' => 'Female',
                'country' => 'Sri Lanka',
                'cumulative_credits_earned' => 360,
                'cumulative_grade_point_average' => '8.7',
                'proof_type' => 'Passport',
                'proof_id' => 'N11353763',
                'reference_no' => 'VR1701-BEC-FC-B25',
                'course_name' => 'Bachelor of Early childhood Education',
                'course_duration' => '3 Years',
                'course_start_date' => '2021-09',
                'course_end_date' => '2024-09',
                'awarding_date' => '2024-10',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 1,
                'created_at' => '2025-01-01 18:06:03',
                'updated_at' => '2025-01-17 09:00:06',
            ],
            [
                'id' => 25,
                'student_id' => '158034',
                'student_name' => 'Ramesh Joseph Raymond Mahendran',
                'student_email' => 'ramesh@eureka.lk',
                'student_phone' => '+1 778 580 5426 14',
                'student_address' => 'COLOMBO, SRI LANKA',
                'student_dob' => '1972-07-01',
                'gender' => 'Male',
                'country' => 'Srilanka',
                'cumulative_credits_earned' => 180,
                'cumulative_grade_point_average' => '7.7',
                'proof_type' => 'Passport',
                'proof_id' => 'N8725240',
                'reference_no' => 'VR1703-MBA-FC-B26',
                'course_name' => 'MBA in International Business',
                'course_duration' => '1 year',
                'course_start_date' => '2023-02',
                'course_end_date' => '2024-02',
                'awarding_date' => '2024-02',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 1,
                'created_at' => '2025-01-27 06:57:49',
                'updated_at' => '2025-03-18 05:18:37',
            ],
            [
                'id' => 27,
                'student_id' => '158035',
                'student_name' => 'Uruthirapathy Kalaiarasan',
                'student_email' => 'Uruthirapathy11@gmail.com',
                'student_phone' => '0764567891',
                'student_address' => 'COLOMBO, SRI LANKA',
                'student_dob' => '1995-03-10',
                'gender' => 'Male',
                'country' => 'Sri Lanka',
                'cumulative_credits_earned' => 360,
                'cumulative_grade_point_average' => '8.3',
                'proof_type' => 'Passport',
                'proof_id' => 'N9015285',
                'reference_no' => 'VR1704-BM-FC-B27',
                'course_name' => 'Bachelor of Business Management (Hons)',
                'course_duration' => '3 years',
                'course_start_date' => '2016-02',
                'course_end_date' => '2019-02',
                'awarding_date' => '2019-02',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 2,
                'created_at' => '2025-04-25 15:14:36',
                'updated_at' => '2025-04-25 15:14:36',
            ],
            [
                'id' => 28,
                'student_id' => '158036',
                'student_name' => 'Navaneethan Jeyasenthuran',
                'student_email' => 'jsenthurandp2024@gmail.com',
                'student_phone' => '0789067880',
                'student_address' => 'CHULIPURAM CENTER, CHULIPURAM, JAFFNA',
                'student_dob' => '1994-07-30',
                'gender' => 'Male',
                'country' => 'Sri Lanka',
                'cumulative_credits_earned' => 360,
                'cumulative_grade_point_average' => '8.3',
                'proof_type' => 'Nic',
                'proof_id' => '942122586V',
                'reference_no' => 'VR1704-BM-FC-B28',
                'course_name' => 'Bachelor of Business Management',
                'course_duration' => '3 years',
                'course_start_date' => '2016-02',
                'course_end_date' => '2019-02',
                'awarding_date' => '2019-02',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 1,
                'created_at' => '2025-05-05 03:01:37',
                'updated_at' => '2025-05-05 03:01:37',
            ],
            [
                'id' => 29,
                'student_id' => '158037',
                'student_name' => 'Maheswaren Jeewan Pradeep John',
                'student_email' => 'jeewan_pradeep@live.com',
                'student_phone' => '+604 818 8937',
                'student_address' => "13380 108 Avenue, Surrey, BC\n ( Postal Code : V3T 0E7)",
                'student_dob' => '1984-03-31',
                'gender' => 'Male',
                'country' => 'Sri Lanka',
                'cumulative_credits_earned' => 180,
                'cumulative_grade_point_average' => '7.5',
                'proof_type' => 'Nic',
                'proof_id' => '840911608V',
                'reference_no' => 'VR1706-MBA-FC-B29',
                'course_name' => 'Master of Business Administration',
                'course_duration' => '1 year',
                'course_start_date' => '2024-02',
                'course_end_date' => '2025-02',
                'awarding_date' => '2025-02',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 1,
                'created_at' => '2025-06-04 04:32:06',
                'updated_at' => '2025-06-05 08:57:00',
            ],
            [
                'id' => 30,
                'student_id' => '158038',
                'student_name' => 'Gardi Arachchige Binuka Shavinda Perera',
                'student_email' => 'shavindaperera00@gmail.com',
                'student_phone' => '+94769224623',
                'student_address' => "NO 196, GALLE ESTATE, THORAYAYA\nKurunagala",
                'student_dob' => '1998-09-01',
                'gender' => 'Male',
                'country' => 'Sri Lanka',
                'cumulative_credits_earned' => 360,
                'cumulative_grade_point_average' => '8.1',
                'proof_type' => 'Nic',
                'proof_id' => '982451558v',
                'reference_no' => 'VR1707-AF-FC-B30',
                'course_name' => 'Bachelor of Accounting and Finance',
                'course_duration' => '3 years',
                'course_start_date' => '2022-02',
                'course_end_date' => '2025-02',
                'awarding_date' => '2025-02',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 1,
                'created_at' => '2025-06-10 09:55:53',
                'updated_at' => '2025-07-01 11:31:01',
            ],
            [
                'id' => 31,
                'student_id' => '158039',
                'student_name' => 'Weerasubramiaman Andaruban',
                'student_email' => 'wanandaruban@gmail.com',
                'student_phone' => '9468233369',
                'student_address' => 'Alwis place, Colombo 13',
                'student_dob' => '1982-05-26',
                'gender' => 'Male',
                'country' => 'Sri Lanka',
                'cumulative_credits_earned' => 180,
                'cumulative_grade_point_average' => '4.0',
                'proof_type' => 'Nic',
                'proof_id' => '821473233V',
                'reference_no' => 'VR1708-AF-FC-B31',
                'course_name' => 'Masters Financial Management and Accounting',
                'course_duration' => '1 year',
                'course_start_date' => '2011-02',
                'course_end_date' => '2012-02',
                'awarding_date' => '2012-02',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 1,
                'created_at' => '2025-06-10 16:15:24',
                'updated_at' => '2025-06-10 16:15:24',
            ],
            [
                'id' => 32,
                'student_id' => '158040',
                'student_name' => 'Munusamy Yogendra',
                'student_email' => 'prabuyogendra@gmail.com',
                'student_phone' => '770188441',
                'student_address' => 'B, 46 2/2, NHS Maligawatta, Colombo 10',
                'student_dob' => '1982-12-12',
                'gender' => 'Male',
                'country' => 'Sri Lanka',
                'cumulative_credits_earned' => null,
                'cumulative_grade_point_average' => null,
                'proof_type' => 'Passport',
                'proof_id' => 'N9462000',
                'reference_no' => 'VR1709-BMM-FC-B32',
                'course_name' => 'Bachelor of Business Management (Hons)',
                'course_duration' => '1 year',
                'course_start_date' => '2022-02',
                'course_end_date' => '2023-02',
                'awarding_date' => '2023-02',
                'center_name' => 'London Business Campus',
                'status' => 'Verified',
                'created_by' => 1,
                'created_at' => '2025-07-09 08:29:35',
                'updated_at' => '2025-07-09 08:29:35',
            ],
        ];

        \DB::table('old_certificates')->insert($oldCertificates);
    }
}
