<?php

return [
    ['nationality' => 'Afghan', 'dial_code' => '+93'],
    ['nationality' => 'Albanian', 'dial_code' => '+355'],
    ['nationality' => 'Algerian', 'dial_code' => '+213'],
    ['nationality' => 'American', 'dial_code' => '+1'],
    ['nationality' => 'Andorran', 'dial_code' => '+376'],
    ['nationality' => 'Angolan', 'dial_code' => '+244'],
    ['nationality' => 'Antiguan or Barbudan', 'dial_code' => '+1-268'],
    ['nationality' => 'Argentine', 'dial_code' => '+54'],
    ['nationality' => 'Armenian', 'dial_code' => '+374'],
    ['nationality' => 'Australian', 'dial_code' => '+61'],
    ['nationality' => 'Austrian', 'dial_code' => '+43'],
    ['nationality' => 'Azerbaijani', 'dial_code' => '+994'],
    ['nationality' => 'Bahamian', 'dial_code' => '+1-242'],
    ['nationality' => 'Bahraini', 'dial_code' => '+973'],
    ['nationality' => 'Bangladeshi', 'dial_code' => '+880'],
    ['nationality' => 'Barbadian', 'dial_code' => '+1-246'],
    ['nationality' => 'Basotho', 'dial_code' => '+266'],
    ['nationality' => 'Belarusian', 'dial_code' => '+375'],
    ['nationality' => 'Belgian', 'dial_code' => '+32'],
    ['nationality' => 'Belizean', 'dial_code' => '+501'],
    ['nationality' => 'Beninese', 'dial_code' => '+229'],
    ['nationality' => 'Bhutanese', 'dial_code' => '+975'],
    ['nationality' => 'Bolivian', 'dial_code' => '+591'],
    ['nationality' => 'Bosnian or Herzegovinian', 'dial_code' => '+387'],
    ['nationality' => 'Botswanan', 'dial_code' => '+267'],
    ['nationality' => 'Brazilian', 'dial_code' => '+55'],
    ['nationality' => 'British', 'dial_code' => '+44'],
    ['nationality' => 'Bruneian', 'dial_code' => '+673'],
    ['nationality' => 'Bulgarian', 'dial_code' => '+359'],
    ['nationality' => 'Burkinabe', 'dial_code' => '+226'],
    ['nationality' => 'Burundian', 'dial_code' => '+257'],
    ['nationality' => 'Cabo Verdean', 'dial_code' => '+238'],
    ['nationality' => 'Cambodian', 'dial_code' => '+855'],
    ['nationality' => 'Cameroonian', 'dial_code' => '+237'],
    ['nationality' => 'Canadian', 'dial_code' => '+1'],
    ['nationality' => 'Central African', 'dial_code' => '+236'],
    ['nationality' => 'Chadian', 'dial_code' => '+235'],
    ['nationality' => 'Chilean', 'dial_code' => '+56'],
    ['nationality' => 'Chinese', 'dial_code' => '+86'],
    ['nationality' => 'Colombian', 'dial_code' => '+57'],
    ['nationality' => 'Comoran', 'dial_code' => '+269'],
    ['nationality' => 'Congolese', 'dial_code' => '+242'],
    ['nationality' => 'Congolese (Democratic Republic of the Congo)', 'dial_code' => '+243'],
    ['nationality' => 'Costa Rican', 'dial_code' => '+506'],
    ['nationality' => 'Croatian', 'dial_code' => '+385'],
    ['nationality' => 'Cuban', 'dial_code' => '+53'],
    ['nationality' => 'Cypriot', 'dial_code' => '+357'],
    ['nationality' => 'Czech', 'dial_code' => '+420'],
    ['nationality' => 'Danish', 'dial_code' => '+45'],
    ['nationality' => 'Djiboutian', 'dial_code' => '+253'],
    ['nationality' => 'Dominican', 'dial_code' => '+1-767'],
    ['nationality' => 'Dominican Republic citizen', 'dial_code' => '+1-809'],
    ['nationality' => 'Dutch', 'dial_code' => '+31'],
    ['nationality' => 'East Timorese', 'dial_code' => '+670'],
    ['nationality' => 'Ecuadorian', 'dial_code' => '+593'],
    ['nationality' => 'Egyptian', 'dial_code' => '+20'],
    ['nationality' => 'Emirati', 'dial_code' => '+971'],
    ['nationality' => 'Equatorial Guinean', 'dial_code' => '+240'],
    ['nationality' => 'Eritrean', 'dial_code' => '+291'],
    ['nationality' => 'Estonian', 'dial_code' => '+372'],
    ['nationality' => 'Swazi', 'dial_code' => '+268'],
    ['nationality' => 'Ethiopian', 'dial_code' => '+251'],
    ['nationality' => 'Fijian', 'dial_code' => '+679'],
    ['nationality' => 'Filipino', 'dial_code' => '+63'],
    ['nationality' => 'Finnish', 'dial_code' => '+358'],
    ['nationality' => 'French', 'dial_code' => '+33'],
    ['nationality' => 'Gabonese', 'dial_code' => '+241'],
    ['nationality' => 'Gambian', 'dial_code' => '+220'],
    ['nationality' => 'Georgian', 'dial_code' => '+995'],
    ['nationality' => 'German', 'dial_code' => '+49'],
    ['nationality' => 'Ghanaian', 'dial_code' => '+233'],
    ['nationality' => 'Greek', 'dial_code' => '+30'],
    ['nationality' => 'Grenadian', 'dial_code' => '+1-473'],
    ['nationality' => 'Guatemalan', 'dial_code' => '+502'],
    ['nationality' => 'Guinean', 'dial_code' => '+224'],
    ['nationality' => 'Guinea-Bissauan', 'dial_code' => '+245'],
    ['nationality' => 'Guyanese', 'dial_code' => '+592'],
    ['nationality' => 'Haitian', 'dial_code' => '+509'],
    ['nationality' => 'Honduran', 'dial_code' => '+504'],
    ['nationality' => 'Hungarian', 'dial_code' => '+36'],
    ['nationality' => 'Icelandic', 'dial_code' => '+354'],
    ['nationality' => 'Indian', 'dial_code' => '+91'],
    ['nationality' => 'Indonesian', 'dial_code' => '+62'],
    ['nationality' => 'Iranian', 'dial_code' => '+98'],
    ['nationality' => 'Iraqi', 'dial_code' => '+964'],
    ['nationality' => 'Irish', 'dial_code' => '+353'],
    ['nationality' => 'Israeli', 'dial_code' => '+972'],
    ['nationality' => 'Italian', 'dial_code' => '+39'],
    ['nationality' => 'Ivorian', 'dial_code' => '+225'],
    ['nationality' => 'Jamaican', 'dial_code' => '+1-876'],
    ['nationality' => 'Japanese', 'dial_code' => '+81'],
    ['nationality' => 'Jordanian', 'dial_code' => '+962'],
    ['nationality' => 'Kazakhstani', 'dial_code' => '+7'],
    ['nationality' => 'Kenyan', 'dial_code' => '+254'],
    ['nationality' => 'I-Kiribati', 'dial_code' => '+686'],
    ['nationality' => 'Kuwaiti', 'dial_code' => '+965'],
    ['nationality' => 'Kyrgyz', 'dial_code' => '+996'],
    ['nationality' => 'Lao', 'dial_code' => '+856'],
    ['nationality' => 'Latvian', 'dial_code' => '+371'],
    ['nationality' => 'Lebanese', 'dial_code' => '+961'],
    ['nationality' => 'Liberian', 'dial_code' => '+231'],
    ['nationality' => 'Libyan', 'dial_code' => '+218'],
    ['nationality' => 'Liechtensteiner', 'dial_code' => '+423'],
    ['nationality' => 'Lithuanian', 'dial_code' => '+370'],
    ['nationality' => 'Luxembourgish', 'dial_code' => '+352'],
    ['nationality' => 'Malagasy', 'dial_code' => '+261'],
    ['nationality' => 'Malawian', 'dial_code' => '+265'],
    ['nationality' => 'Malaysian', 'dial_code' => '+60'],
    ['nationality' => 'Maldivian', 'dial_code' => '+960'],
    ['nationality' => 'Malian', 'dial_code' => '+223'],
    ['nationality' => 'Maltese', 'dial_code' => '+356'],
    ['nationality' => 'Marshallese', 'dial_code' => '+692'],
    ['nationality' => 'Mauritanian', 'dial_code' => '+222'],
    ['nationality' => 'Mauritian', 'dial_code' => '+230'],
    ['nationality' => 'Mexican', 'dial_code' => '+52'],
    ['nationality' => 'Micronesian', 'dial_code' => '+691'],
    ['nationality' => 'Moldovan', 'dial_code' => '+373'],
    ['nationality' => 'Monacan', 'dial_code' => '+377'],
    ['nationality' => 'Mongolian', 'dial_code' => '+976'],
    ['nationality' => 'Montenegrin', 'dial_code' => '+382'],
    ['nationality' => 'Moroccan', 'dial_code' => '+212'],
    ['nationality' => 'Mozambican', 'dial_code' => '+258'],
    ['nationality' => 'Burmese', 'dial_code' => '+95'],
    ['nationality' => 'Namibian', 'dial_code' => '+264'],
    ['nationality' => 'Nauruan', 'dial_code' => '+674'],
    ['nationality' => 'Nepalese', 'dial_code' => '+977'],
    ['nationality' => 'New Zealander', 'dial_code' => '+64'],
    ['nationality' => 'Nicaraguan', 'dial_code' => '+505'],
    ['nationality' => 'Nigerian', 'dial_code' => '+234'],
    ['nationality' => 'Nigerien', 'dial_code' => '+227'],
    ['nationality' => 'North Korean', 'dial_code' => '+850'],
    ['nationality' => 'North Macedonian', 'dial_code' => '+389'],
    ['nationality' => 'Norwegian', 'dial_code' => '+47'],
    ['nationality' => 'Omani', 'dial_code' => '+968'],
    ['nationality' => 'Pakistani', 'dial_code' => '+92'],
    ['nationality' => 'Palauan', 'dial_code' => '+680'],
    ['nationality' => 'Palestinian', 'dial_code' => '+970'],
    ['nationality' => 'Panamanian', 'dial_code' => '+507'],
    ['nationality' => 'Papua New Guinean', 'dial_code' => '+675'],
    ['nationality' => 'Paraguayan', 'dial_code' => '+595'],
    ['nationality' => 'Peruvian', 'dial_code' => '+51'],
    ['nationality' => 'Polish', 'dial_code' => '+48'],
    ['nationality' => 'Portuguese', 'dial_code' => '+351'],
    ['nationality' => 'Qatari', 'dial_code' => '+974'],
    ['nationality' => 'Romanian', 'dial_code' => '+40'],
    ['nationality' => 'Russian', 'dial_code' => '+7'],
    ['nationality' => 'Rwandan', 'dial_code' => '+250'],
    ['nationality' => 'Saint Kitts and Nevis', 'dial_code' => '+1-869'],
    ['nationality' => 'Saint Lucian', 'dial_code' => '+1-758'],
    ['nationality' => 'Saint Vincentian', 'dial_code' => '+1-784'],
    ['nationality' => 'Salvadoran', 'dial_code' => '+503'],
    ['nationality' => 'Samoan', 'dial_code' => '+685'],
    ['nationality' => 'San Marinese', 'dial_code' => '+378'],
    ['nationality' => 'Sao Tomean', 'dial_code' => '+239'],
    ['nationality' => 'Saudi Arabian', 'dial_code' => '+966'],
    ['nationality' => 'Senegalese', 'dial_code' => '+221'],
    ['nationality' => 'Serbian', 'dial_code' => '+381'],
    ['nationality' => 'Seychellois', 'dial_code' => '+248'],
    ['nationality' => 'Sierra Leonean', 'dial_code' => '+232'],
    ['nationality' => 'Singaporean', 'dial_code' => '+65'],
    ['nationality' => 'Slovak', 'dial_code' => '+421'],
    ['nationality' => 'Slovenian', 'dial_code' => '+386'],
    ['nationality' => 'Solomon Islander', 'dial_code' => '+677'],
    ['nationality' => 'Somali', 'dial_code' => '+252'],
    ['nationality' => 'South African', 'dial_code' => '+27'],
    ['nationality' => 'South Korean', 'dial_code' => '+82'],
    ['nationality' => 'South Sudanese', 'dial_code' => '+211'],
    ['nationality' => 'Spanish', 'dial_code' => '+34'],
    ['nationality' => 'Sri Lankan', 'dial_code' => '+94'],
    ['nationality' => 'Sudanese', 'dial_code' => '+249'],
    ['nationality' => 'Surinamese', 'dial_code' => '+597'],
    ['nationality' => 'Swedish', 'dial_code' => '+46'],
    ['nationality' => 'Swiss', 'dial_code' => '+41'],
    ['nationality' => 'Syrian', 'dial_code' => '+963'],
    ['nationality' => 'Taiwanese', 'dial_code' => '+886'],
    ['nationality' => 'Tajik', 'dial_code' => '+992'],
    ['nationality' => 'Tanzanian', 'dial_code' => '+255'],
    ['nationality' => 'Thai', 'dial_code' => '+66'],
    ['nationality' => 'Togolese', 'dial_code' => '+228'],
    ['nationality' => 'Tongan', 'dial_code' => '+676'],
    ['nationality' => 'Trinidadian or Tobagonian', 'dial_code' => '+1-868'],
    ['nationality' => 'Tunisian', 'dial_code' => '+216'],
    ['nationality' => 'Turkish', 'dial_code' => '+90'],
    ['nationality' => 'Turkmen', 'dial_code' => '+993'],
    ['nationality' => 'Tuvaluan', 'dial_code' => '+688'],
    ['nationality' => 'Ugandan', 'dial_code' => '+256'],
    ['nationality' => 'Ukrainian', 'dial_code' => '+380'],
    ['nationality' => 'Uruguayan', 'dial_code' => '+598'],
    ['nationality' => 'Uzbek', 'dial_code' => '+998'],
    ['nationality' => 'Vanuatuan', 'dial_code' => '+678'],
    ['nationality' => 'Vatican citizen', 'dial_code' => '+379'],
    ['nationality' => 'Venezuelan', 'dial_code' => '+58'],
    ['nationality' => 'Vietnamese', 'dial_code' => '+84'],
    ['nationality' => 'Yemeni', 'dial_code' => '+967'],
    ['nationality' => 'Zambian', 'dial_code' => '+260'],
    ['nationality' => 'Zimbabwean', 'dial_code' => '+263'],
    ['nationality' => 'Other', 'dial_code' => ''],
];
