name: 🚀 Deploy LBC verification 

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-dev --optimize-autoloader

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install npm packages
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER_PROD }}
          username: ${{ secrets.FTP_USERNAME_PROD }}
          password: ${{ secrets.FTP_PASSWORD_PROD }}
          server-dir: /
          timeout: 86400000
